### ISSUE TITLE
extremely slow window leveling

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstone#112]
we are testing cornerstone and window leveling very large images (mammo) is extremely slow, sometimes more than 5 seconds wait, which makes it unusable for us.

Is there any way to increase window level performance ?

Also  is it possible to break ongoing window leveling operation when another one starts ? ie when the mouse is dragged further ?

Thanks !

**Comment by swederik** [comment]
What values are you seeing for 'renderTimeInMs'? What resolution are your images? 5 seconds is very high. Can you post a simple example with your image? Or provide an anonymized version?

You can use WebGL to improve performance. See:

https://rawgit.com/chafey/cornerstone/master/example/WebGL/index.html

I'm not sure I follow the last question. Do you want to stop redrawing on one canvas when interaction on another one starts?

**Comment by jpambrun** [comment]
This may be the wrong min/max pixel values issue with out-of-range lut lookups.
It is most likely a deop issue of some sort.

As with the second point. It is not possible to break rendering. All this time is spent in StoredPixelToCanvas in a very tight loop, adding an interruption condition will further slow things down.
However, with the RAF method, it should be 'stacking' window/level events so that the same amount of mouse movements would cause the same change in W/L regardless of the frame rate. If it is not, then there is probably an issue in cornerstoneTools.

**Comment by kofifus** [comment]
Here is an image that is very slow to window level:
    https://www.dropbox.com/s/jtoj5vi4ak4rlmj/Cornerstone_windowlevel.zip?dl=0

Can you tell what's the problem there ?

**Comment by jpambrun** [comment]
storedPixelDataToCanvasImageData gets deoptimized again. I don't know
exactly why yet. I will investigate more later this week.

**Comment by hardmaster92** [comment]
I experience slow window level change (and manual rotation) on some DX, CR and MG images with very high resolution but I guess it's normal.

**Comment by kofifus** [comment]
jpambrun any update on this ?

**Comment by swederik** [comment]
There were some performance improvements added here: https://github.com/chafey/cornerstone/commit/484ab38244438cb75a3c536149160d0284d823a7

How large are the images? It's also very possible that your image has incorrect min/max pixel values as stated above. We plan to add an option to the WADO Image Loader which will fix this for you, but haven't gotten around to it yet.

**Comment by kofifus** [comment]
Thx swederik !

Did you get a chance to look at thesample image I sent (https://www.dropbox.com/s/jtoj5vi4ak4rlmj/Cornerstone_windowlevel.zip?dl=0)

The image is not small but still window leveling is so slow itseems something else may be going on ...

**Comment by jpambrun** [comment]
Using [0], it takes about 25 ms on my PC (an Intel(R) Core(TM) i7-7700K CPU
@ 4.20GHz) to apply the lut with the provided image.
This is what I expect for a 16.7 megapixel image since I typically get
about 0.7 megapixel/ms throughput in storedPixelDataToCanvasImageData.
When you factor everything, each frame takes between ~50 ms to render

You can try the WebGL backend that provides much faster window leveling.
With this setup I get a solid 60 fps (render time  <<16 ms) with about 1.5
ms of GPU time (on a GTX 1080).

Hope this helps,
JF

[0]
https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

**Comment by kofifus** [comment]
I don't know how to measure the time, but if I load that image into the example here https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

And then window level with the left mouse button, it is very laggy, seems to be about 1-2 seconds for the image to update with a new window level.

Thx

**Comment by jpambrun** [comment]
From [0] (with a very outdated cornerstone)
http://dl.dropbox.com/u/168338/screenshots/20170522195305.png
We see the two image are render per displayed frame which is a bug that was
fixed long ago. The lut application takes ~25ms

With an up-to-date cornerstone :
http://dl.dropbox.com/u/168338/screenshots/20170522195642.png
Complete render now takes ~45ms, lut application is still at ~25ms (now
t.default because of minification)

With webgl
http://dl.dropbox.com/u/168338/screenshots/20170522195541.png

**Comment by kofifus** [comment]
Sorry I don't understand. Do you mean the example is of outdated code and the latest version is faster ? if so can the example be updated ?

thx

**Comment by jpambrun** [comment]
Yes, I was referring to the cornerstone lib version.

I just updated it; it should feel a bit faster.

**Comment by kofifus** [comment]
yes that is quite a bit faster !
