### ISSUE TITLE
Performance issues when adjusting brightness/contrast (WW/WC) on larger images

### ISSUE THREAD

**Issue by csengineer13** [chafey/cornerstone#117]
I'm noticing > 150ms render time on my relatively small image (650x650) as I adjust WW/WC. As the current implementation must apply filter affects to every pixel, I can imagine that performance continues to decrease drastically for larger images.

My current workaround:
- Load Image
- Modify filter effects to apply [CSS Filters](http://caniuse.com/#feat=css-filters) to Canvas element
- If effects need to persist, apply them to each pixel before persisting

I'm more than happy to whip up and contribute an example, but I'm curious to hear thoughts or other potential workarounds before writing anything up.

**Comment by jpambrun** [comment]
I'm not sure I understand, the purpose of the VOI function is to correctly
convert from 16 bit modality pixel values to 8 bit display pixel values.

My understanding is that the canvas pixel data on which the CSS filter is
applied is a already a Uint8ClampedArray ? No?

**Comment by csengineer13** [comment]
Maybe an example would help show what I mean. Give this a try:

http://codepen.io/csengineer13/full/dbb92cc1138b18bdb3d9f9e857a7b995/

On the left, the default cornerstone example for updating brightness/contrast. On the right, a CSS3 based filter. Hacked together, but I hope it's enough to convey my issue. The contrast/brightness is not 1:1, nor is the scale, but I think you can achieve very similar results with a bit of tinkering, and see a decent performance boost. 

This is not my area of expertise; I'm just trying to solve for a performance issue I noticed while playing with this library. If my attempt is fundamentally flawed, or if there is a better approach, I am 100% open (and excited ) to learning why/how.

**Comment by jpambrun** [comment]
First off, this issue was mostly fixed already. I could get the render time
from 300+ms to 10 ms on your demo by updating cornerstone to the latest
version (using [1]).

Most importantly, you are loading an 8 bit file (a png). This is not the
typical use case. Typical medical image has higher dynamic range 12-16 bit
per pixel in grayscale. The data needs to be converted to 8 bit using the
VOI transform before it hits the canvas making the proposed solution
unsuitable.

Don't let this stop you from proposing other improvements.

[1] https://rawgit.com/chafey/cornerstone/master/dist/cornerstone.js

**Comment by csengineer13** [comment]
Amazing and quick response @jpambrum!

It may be worth noting that I pulled in the version of Cornerstone that is referenced in CornerstoneTools repo.
