### ISSUE TITLE
Browser runs out of memory on some huge ES series

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstone#119]
I guess it is obvious that I get this issue and it's normal if it happens due to the browser limitations but I decided to post here just to make sure that this can never be fixed.
So basically when I try to load huge dcm files containing ES series (for example 1 GB) I patiently wait for the browser to load the big file while monitoring the memory and watching it getting higher and higher. 
When I try this with Google Chrome - I can see the memory reaching at 2GB and I get message that the browser has run out of memory.
Then I tried with Waterfox (because it's 64-bit and can use more memory). It reached something like 4-5 GB of memory and I got a message that Firefox usually shows when some script is taking too much time to load and let's you chose to either block it or keep waiting. I chose the option to keep waiting and did it several times more and finally decided to quit because it never loaded.

So I was wondering if it's possible somehow to optimize this (even on the server side if needed) or I just have to admit that loading such big files using the browser is pointless and it's better to use a desktop viewer in these cases?

**Comment by jpambrun** [comment]
On Chrome Linux, the upper limit that a process can reach is about 2gb.
Unfortunately, multiple tabs can be grouped into a single process reducing
available memory further. On Windows, this appears to be closer to 4gb.

Firefox does not appear to have any such limitations, I could allocate up
30gb in a single tab.
The long running issue can be avoided by using webworker instead of the
main tread.

In any case, loading 1gb of data should not consume more than 2gb and just
while loading.

JF

**Comment by hardmaster92** [comment]
I use wado web worker. I will make a working example for you soon :)
