### ISSUE TITLE
In frontend case, How can I get base64 encode from dicom file ?

### ISSUE THREAD

**Issue by xenophon566** [chafey/cornerstone#62]
How can I get base64 encode from dicom file to feed "image108Base64" just like your example code ?

**Comment by swederik** [comment]
You probably don't want to do that. I guess you should be using the WADO Image Loader instead of trying to convert to base64. The base64 part of the code is only meant for the examples, since it prevents the examples pages from having to request the data from somewhere else.

Check the examples of https://github.com/chafey/cornerstoneWADOImageLoader

**Comment by xenophon566** [comment]
Thanks for your prompt reply.

**Comment by vivek00712** [comment]
please tell me how can i get image108Base64 encoder and decoder because i want to store images in my SQL Database so i can retrieve and store it into database if i have image in base64 formate.
So kindly guide me how to set image108Base64 for dicom image that you explain in your example by defining static set of image with image108Base64 formate.
Please do the needfull
Thanks in Advance
Vivek

**Comment by pujasanjay** [comment]
Sir

I was trying to use the example 
cornerstoneWADOImageLoader-master/examples/wadouri

I keep getting error with a local file 

I guess the problem seems to be in 

function ($, cornerstone, cornerstoneWADOImageLoader) {
    "use strict";
    function xhrRequest(url, imageId) 

Apparently the url is null and imageid = "wadouri:a/1.3.46.670589.11.8362.5.0.2672.2014092515570109004.dcm"


Kindly help

**Comment by chafey** [comment]
@pujasanjay please do not post on closed issues that are unrelated to your question.  Keeping this closed
