### ISSUE TITLE
Display .dcm and playing CT Scans in a bootstrap modal

### ISSUE THREAD

**Issue by meppiel** [chafey/cornerstone#65]
Hello!

I'm having a bit of trouble using the library in a bootstrap modal.

http://stackoverflow.com/questions/38032342/bootstrap-modal-cornerstone-js-library

Any ideas?

**Comment by chafey** [comment]
My guess is that you are calling enable() when the dialog is not yet visible so cornerstone sees the size as 0x0.  Try calling resize() after the dialog is visible?

**Comment by chafey** [comment]
Any update on this?

**Comment by chafey** [comment]
If this answered our question please close

**Comment by swederik** [comment]
I believe the point of this issue is that Cornerstone will determine it's canvas size based on the parent element size. If your parent element is not on screen, your canvas will be 0x0. The solution should be to either:

- Wait until your element is on screen (and has real dimensions) to enable Cornerstone on it, or as @chafey states above, force a resize after the element has appeared.

I'll close this now since the question appears to be answered.
