### ISSUE TITLE
Issue with imageCache.decache and fix for it

### ISSUE THREAD

**Issue by davew945** [chafey/cornerstone#72]
I am using cornerstone 0.9.0 with cornerstoneWADOImageLoader-0.13.3 and cornerstoneWebImageLoader-0.6.0. When I call cornerstone.imageCache.purgeCache(), on the call to decache(), if imagePromise does not have reject() method, an exception occurs and the cache is not purged.
If I protect the call, the purge works correctly. cornerstone-0.9.0.js line 555.
if (imagePromise.reject) {
  imagePromise.reject();
  }
Thank you for fixing this.

**Comment by swederik** [comment]
Hi Dave,

This was an issue with the image loaders not returning Deferred instead of a Promise. I think this is fixed in the latest version of the WADO Image Loader. I know one recent fix was merged here: https://github.com/chafey/cornerstoneWADOImageLoader/pull/74

I'll close this now. Please update WADO Image Loader and reopen this issue if you run into the problem again.

Thanks for the report!
